/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import model.KepalaPerpus;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author zidan
 */
public class DashboardKepalaPerpus extends javax.swing.JPanel {

    /**
     * Creates new form DashboardMember
     */
    public DashboardKepalaPerpus(KepalaPerpus kepala) {
        initComponents();
        this.kepala = kepala;
        jumlahBuku.setText(Integer.toString(kepala.getJumlahBuku()));
        tableBuku.setModel(kepala.lihatDataBuku());
    }
    
    KepalaPerpus kepala;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        card_dataBuku = new custom.Custom_JPanelRounded();
        lb_dataBuku = new javax.swing.JLabel();
        lb_icon = new javax.swing.JLabel();
        jumlahBuku = new javax.swing.JLabel();
        card_akun = new custom.Custom_JPanelRounded();
        lb_akun = new javax.swing.JLabel();
        lb_icon1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBuku = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        card_dataBuku.setBackground(new java.awt.Color(0, 153, 204));
        card_dataBuku.setRoundBottomLeft(30);
        card_dataBuku.setRoundBottomRight(30);
        card_dataBuku.setRoundTopLeft(30);
        card_dataBuku.setRoundTopRight(30);
        card_dataBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card_dataBukuMouseClicked(evt);
            }
        });

        lb_dataBuku.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lb_dataBuku.setForeground(new java.awt.Color(255, 255, 255));
        lb_dataBuku.setText("DATA BUKU");

        lb_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_book_70px.png"))); // NOI18N

        jumlahBuku.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jumlahBuku.setForeground(new java.awt.Color(255, 255, 255));
        jumlahBuku.setText("9");

        javax.swing.GroupLayout card_dataBukuLayout = new javax.swing.GroupLayout(card_dataBuku);
        card_dataBuku.setLayout(card_dataBukuLayout);
        card_dataBukuLayout.setHorizontalGroup(
            card_dataBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_dataBukuLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(card_dataBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_dataBuku)
                    .addGroup(card_dataBukuLayout.createSequentialGroup()
                        .addComponent(jumlahBuku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_icon)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        card_dataBukuLayout.setVerticalGroup(
            card_dataBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_dataBukuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lb_dataBuku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(card_dataBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lb_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahBuku))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        card_akun.setBackground(new java.awt.Color(0, 153, 204));
        card_akun.setPreferredSize(new java.awt.Dimension(310, 150));
        card_akun.setRoundBottomLeft(30);
        card_akun.setRoundBottomRight(30);
        card_akun.setRoundTopLeft(30);
        card_akun.setRoundTopRight(30);
        card_akun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                card_akunMouseClicked(evt);
            }
        });

        lb_akun.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lb_akun.setForeground(new java.awt.Color(255, 255, 255));
        lb_akun.setText("AKUN");

        lb_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_person_70px.png"))); // NOI18N

        javax.swing.GroupLayout card_akunLayout = new javax.swing.GroupLayout(card_akun);
        card_akun.setLayout(card_akunLayout);
        card_akunLayout.setHorizontalGroup(
            card_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_akunLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(card_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card_akunLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lb_akun))
                    .addComponent(lb_icon1))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        card_akunLayout.setVerticalGroup(
            card_akunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_akunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_akun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_icon1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tableBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tableBuku.setRowHeight(30);
        jScrollPane1.setViewportView(tableBuku);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Daftar Buku");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(card_dataBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(card_akun, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(card_akun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(card_dataBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void card_dataBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card_dataBukuMouseClicked
        this.removeAll();
        this.add(new DataBukuKepalaPerpustakaan(kepala));
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_card_dataBukuMouseClicked

    private void card_akunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_card_akunMouseClicked
        try {
            this.removeAll();
            this.add(new DetailKepalaPerpus(kepala));
            this.repaint();
            this.revalidate();
        } catch (SQLException ex) {
            Logger.getLogger(DashboardPetugasPerpus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_card_akunMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private custom.Custom_JPanelRounded card_akun;
    private custom.Custom_JPanelRounded card_dataBuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jumlahBuku;
    private javax.swing.JLabel lb_akun;
    private javax.swing.JLabel lb_dataBuku;
    private javax.swing.JLabel lb_icon;
    private javax.swing.JLabel lb_icon1;
    private javax.swing.JTable tableBuku;
    // End of variables declaration//GEN-END:variables
}
