package view;


import java.awt.Color;
import service.DatabaseConnection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author zidan
 */
public class from_daftar extends javax.swing.JFrame {
    int xx, xy;
    /**
     * Creates new form from_login
     */
    public from_daftar() {
        initComponents();
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_kiri = new custom.Custom_JPanelRounded();
        jLabel3 = new javax.swing.JLabel();
        usernameTextField = new custom.Custom_TextField();
        custom_ButonRounded2 = new custom.Custom_ButonRounded();
        passwordTextField = new custom.Custom_PasswordField();
        usernameTextField1 = new custom.Custom_TextField();
        usernameTextField2 = new custom.Custom_TextField();
        usernameTextField3 = new custom.Custom_TextField();
        usernameTextField4 = new custom.Custom_TextField();
        pn_kanan = new custom.Custom_JPanelRounded();
        tombol_close = new javax.swing.JLabel();
        gambar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_kiri.setBackground(new java.awt.Color(255, 255, 255));
        pn_kiri.setRoundBottomLeft(50);
        pn_kiri.setRoundTopLeft(50);
        pn_kiri.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel3.setText("Daftar");
        pn_kiri.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        usernameTextField.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        usernameTextField.setLabelText("No. Telepon");
        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        pn_kiri.add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 220, -1));

        custom_ButonRounded2.setForeground(new java.awt.Color(255, 255, 255));
        custom_ButonRounded2.setText("DAFTAR");
        custom_ButonRounded2.setBorderColor(new java.awt.Color(0, 153, 204));
        custom_ButonRounded2.setColor(new java.awt.Color(0, 153, 204));
        custom_ButonRounded2.setColorClick(new java.awt.Color(0, 102, 153));
        custom_ButonRounded2.setColorOver(new java.awt.Color(0, 153, 204));
        custom_ButonRounded2.setRadius(10);
        custom_ButonRounded2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom_ButonRounded2ActionPerformed(evt);
            }
        });
        pn_kiri.add(custom_ButonRounded2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 220, 40));

        passwordTextField.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        passwordTextField.setLabelText("Password");
        passwordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextFieldActionPerformed(evt);
            }
        });
        pn_kiri.add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 220, -1));

        usernameTextField1.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        usernameTextField1.setLabelText("Username");
        usernameTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextField1ActionPerformed(evt);
            }
        });
        pn_kiri.add(usernameTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 220, -1));

        usernameTextField2.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        usernameTextField2.setLabelText("Nama");
        usernameTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextField2ActionPerformed(evt);
            }
        });
        pn_kiri.add(usernameTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 220, -1));

        usernameTextField3.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        usernameTextField3.setLabelText("Alamat");
        usernameTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextField3ActionPerformed(evt);
            }
        });
        pn_kiri.add(usernameTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 220, -1));

        usernameTextField4.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        usernameTextField4.setLabelText("Tanggal Lahir");
        usernameTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextField4ActionPerformed(evt);
            }
        });
        pn_kiri.add(usernameTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 220, -1));

        getContentPane().add(pn_kiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 440));

        pn_kanan.setBackground(new java.awt.Color(255, 255, 255));
        pn_kanan.setRoundBottomRight(50);
        pn_kanan.setRoundTopRight(50);

        tombol_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_close_30px.png"))); // NOI18N
        tombol_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombol_closeMouseClicked(evt);
            }
        });

        gambar.setBackground(new java.awt.Color(255, 255, 255));
        gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/gambarLogin.jpg"))); // NOI18N

        javax.swing.GroupLayout pn_kananLayout = new javax.swing.GroupLayout(pn_kanan);
        pn_kanan.setLayout(pn_kananLayout);
        pn_kananLayout.setHorizontalGroup(
            pn_kananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kananLayout.createSequentialGroup()
                .addGroup(pn_kananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_kananLayout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(tombol_close))
                    .addGroup(pn_kananLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(gambar)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pn_kananLayout.setVerticalGroup(
            pn_kananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kananLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(tombol_close)
                .addGap(44, 44, 44)
                .addComponent(gambar)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        getContentPane().add(pn_kanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 330, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void tombol_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_closeMouseClicked
        dispose();
    }//GEN-LAST:event_tombol_closeMouseClicked
                  
    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void custom_ButonRounded2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom_ButonRounded2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custom_ButonRounded2ActionPerformed

    private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextFieldActionPerformed

    private void usernameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextField1ActionPerformed

    private void usernameTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextField2ActionPerformed

    private void usernameTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextField3ActionPerformed

    private void usernameTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(from_daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(from_daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(from_daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(from_daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new from_daftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private custom.Custom_ButonRounded custom_ButonRounded2;
    private javax.swing.JLabel gambar;
    private javax.swing.JLabel jLabel3;
    private custom.Custom_PasswordField passwordTextField;
    private custom.Custom_JPanelRounded pn_kanan;
    private custom.Custom_JPanelRounded pn_kiri;
    private javax.swing.JLabel tombol_close;
    private custom.Custom_TextField usernameTextField;
    private custom.Custom_TextField usernameTextField1;
    private custom.Custom_TextField usernameTextField2;
    private custom.Custom_TextField usernameTextField3;
    private custom.Custom_TextField usernameTextField4;
    // End of variables declaration//GEN-END:variables
}
