package view;


import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author zidan
 */
public class from_login extends javax.swing.JFrame {
    int xx, xy;
    /**
     * Creates new form from_login
     */
    public from_login() {
        initComponents();
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_kiri = new custom.Custom_JPanelRounded();
        jLabel3 = new javax.swing.JLabel();
        custom_ButonRounded1 = new custom.Custom_ButonRounded();
        custom_TextField3 = new custom.Custom_TextField();
        custom_PasswordField1 = new custom.Custom_PasswordField();
        pn_kanan = new custom.Custom_JPanelRounded();
        tombol_close = new javax.swing.JLabel();
        gambar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pn_kiri.setBackground(new java.awt.Color(255, 255, 255));
        pn_kiri.setRoundBottomLeft(50);
        pn_kiri.setRoundTopLeft(50);
        pn_kiri.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel3.setText(" Welcome ");
        pn_kiri.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 64, -1, -1));

        custom_ButonRounded1.setBorder(null);
        custom_ButonRounded1.setForeground(new java.awt.Color(255, 255, 255));
        custom_ButonRounded1.setText("LOGIN");
        custom_ButonRounded1.setBorderColor(new java.awt.Color(153, 153, 153));
        custom_ButonRounded1.setBorderPainted(false);
        custom_ButonRounded1.setColor(new java.awt.Color(153, 153, 153));
        custom_ButonRounded1.setColorClick(new java.awt.Color(102, 102, 102));
        custom_ButonRounded1.setColorOver(new java.awt.Color(153, 153, 153));
        custom_ButonRounded1.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        custom_ButonRounded1.setRadius(10);
        pn_kiri.add(custom_ButonRounded1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 220, 40));

        custom_TextField3.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        custom_TextField3.setLabelText("Username");
        custom_TextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custom_TextField3ActionPerformed(evt);
            }
        });
        pn_kiri.add(custom_TextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 220, -1));

        custom_PasswordField1.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        custom_PasswordField1.setLabelText("Password");
        pn_kiri.add(custom_PasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 220, -1));

        getContentPane().add(pn_kiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 370));

        pn_kanan.setBackground(new java.awt.Color(255, 255, 255));
        pn_kanan.setRoundBottomRight(50);
        pn_kanan.setRoundTopRight(50);

        tombol_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_close_30px.png"))); // NOI18N
        tombol_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombol_closeMouseClicked(evt);
            }
        });

        gambar.setBackground(new java.awt.Color(255, 255, 255));
        gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/gambarLogin.jpg"))); // NOI18N

        javax.swing.GroupLayout pn_kananLayout = new javax.swing.GroupLayout(pn_kanan);
        pn_kanan.setLayout(pn_kananLayout);
        pn_kananLayout.setHorizontalGroup(
            pn_kananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_kananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tombol_close)
                    .addComponent(gambar))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pn_kananLayout.setVerticalGroup(
            pn_kananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kananLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(tombol_close)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(gambar)
                .addGap(36, 36, 36))
        );

        getContentPane().add(pn_kanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 330, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void tombol_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombol_closeMouseClicked
        dispose();
    }//GEN-LAST:event_tombol_closeMouseClicked

    private void custom_TextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custom_TextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custom_TextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(from_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(from_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(from_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(from_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new from_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private custom.Custom_ButonRounded custom_ButonRounded1;
    private custom.Custom_PasswordField custom_PasswordField1;
    private custom.Custom_TextField custom_TextField3;
    private javax.swing.JLabel gambar;
    private javax.swing.JLabel jLabel3;
    private custom.Custom_JPanelRounded pn_kanan;
    private custom.Custom_JPanelRounded pn_kiri;
    private javax.swing.JLabel tombol_close;
    // End of variables declaration//GEN-END:variables
}
